//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobify.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobApplication
    {
        public int ApplicationId { get; set; }
        public int JobId { get; set; }
        public int JobSeekerId { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Skills { get; set; }
        public string CoverLetter { get; set; }
        public string ResumeLink { get; set; }
        public Nullable<System.DateTime> AppliedAt { get; set; }
    
        public virtual JobPost JobPost { get; set; }
        public virtual JobSeeker JobSeeker { get; set; }
    }
}
