//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobify.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resume
    {
        public int ResumeId { get; set; }
        public Nullable<int> JobSeekerId { get; set; }
        public string ResumeLink { get; set; }
        public Nullable<System.DateTime> UploadedAt { get; set; }
    
        public virtual JobSeeker JobSeeker { get; set; }
    }
}
